#!/usr/bin/env node
/**
 * Email CSS Export Script
 *
 * Generates email-safe inline CSS snippet for Postmark templates
 * Uses only CSS properties that work across major email clients
 *
 * Output: dist/tokens/email-tokens.css
 *
 * Email Client Support:
 * - Gmail, Outlook, Apple Mail, Yahoo Mail
 * - Limited CSS support (no CSS variables, limited flexbox/grid)
 * - Requires inline styles for maximum compatibility
 *
 * Usage:
 *   npm run generate:tokens
 *   or
 *   ts-node scripts/generate-email-css.ts
 *
 * @module scripts/generate-email-css
 * @version 1.0.0
 */

import fs from 'fs';
import path from 'path';

// Import Tailwind config
const tailwindConfigPath = path.resolve(__dirname, '../tailwind.config.js');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const tailwindConfig = require(tailwindConfigPath);

interface ColorScale {
  DEFAULT?: string;
  [key: string]: string | undefined;
}

interface Colors {
  [key: string]: string | ColorScale;
}

interface TailwindTheme {
  extend: {
    colors: Colors;
    fontFamily: {
      [key: string]: string[];
    };
  };
}

const theme = tailwindConfig.theme as TailwindTheme;

/**
 * Get color value from color object
 */
function getColorValue(colorObj: string | ColorScale | undefined, shade?: string | number): string | undefined {
  if (!colorObj) {
    return undefined;
  }
  if (typeof colorObj === 'string') {
    return colorObj;
  }
  if (shade) {
    return colorObj[shade];
  }
  return colorObj.DEFAULT;
}

/**
 * Generate email-safe CSS classes
 */
function generateEmailCSS(): string {
  const colors = theme.extend.colors;
  const fontFamily = theme.extend.fontFamily;

  // Extract key colors
  const primary = getColorValue(colors.primary, 500) || '#066E76';
  const primarySoft = getColorValue(colors.primarySoft, 500) || '#0E9BA7';
  const sustainability = getColorValue(colors.sustainability, 500) || '#16A34A';
  const amber = getColorValue(colors.amber, 500) || '#F97316';
  const critical = getColorValue(colors.critical, 600) || '#DC2626';
  const textMain = getColorValue(colors.text, 'main') || '#0F172A';
  const textSecondary = getColorValue(colors.text, 'secondary') || '#475569';
  const textMuted = getColorValue(colors.text, 'muted') || '#64748B';
  const canvas = getColorValue(colors.canvas) || '#F3F5F7';
  const surface = getColorValue(colors.surface) || '#FFFFFF';
  const borderSubtle = getColorValue(colors.border, 'subtle') || '#E2E8F0';

  // Font stack (email-safe fallbacks)
  const sansStack = fontFamily.sans?.join(', ') || 'Arial, sans-serif';

  const cssContent = `/**
 * Lighthouse Health Design System - Email CSS Tokens
 *
 * Version: 1.0.0 - Luminous Climate Clinical
 * Generated from: tailwind.config.js
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run \`npm run generate:tokens\` to regenerate
 *
 * Email Client Compatibility:
 * - Gmail (web, mobile)
 * - Outlook (2007-2021, 365)
 * - Apple Mail (macOS, iOS)
 * - Yahoo Mail
 * - AOL Mail
 *
 * Usage in Postmark Templates:
 * Copy the inline styles below and apply directly to HTML elements
 *
 * Example:
 *   <h1 style="/* paste from .email-heading-1 below */">Welcome!</h1>
 *   <p style="/* paste from .email-body below */">Your message here.</p>
 */

/* ============================================================================
 * EMAIL BODY
 * ========================================================================== */

/* Base email container */
.email-container {
  max-width: 600px;
  margin: 0 auto;
  background-color: ${canvas};
  font-family: ${sansStack};
  color: ${textMain};
}

/* Email content wrapper (white background) */
.email-content {
  background-color: ${surface};
  padding: 40px 24px;
  border-radius: 8px;
}

/* ============================================================================
 * TYPOGRAPHY
 * ========================================================================== */

/* Heading 1 - Email subject line / main hero */
.email-heading-1 {
  font-family: ${sansStack};
  font-size: 32px;
  line-height: 1.2;
  letter-spacing: -0.02em;
  color: ${textMain};
  margin: 0 0 16px 0;
  font-weight: 600;
}

/* Heading 2 - Section headers */
.email-heading-2 {
  font-family: ${sansStack};
  font-size: 24px;
  line-height: 1.25;
  letter-spacing: -0.015em;
  color: ${textMain};
  margin: 24px 0 12px 0;
  font-weight: 600;
}

/* Heading 3 - Subsection headers */
.email-heading-3 {
  font-family: ${sansStack};
  font-size: 20px;
  line-height: 1.3;
  letter-spacing: -0.01em;
  color: ${textMain};
  margin: 20px 0 8px 0;
  font-weight: 600;
}

/* Body text - Primary content */
.email-body {
  font-family: ${sansStack};
  font-size: 16px;
  line-height: 1.6;
  color: ${textMain};
  margin: 0 0 16px 0;
}

/* Body small - Secondary content */
.email-body-small {
  font-family: ${sansStack};
  font-size: 14px;
  line-height: 1.5;
  color: ${textSecondary};
  margin: 0 0 12px 0;
}

/* Caption / fine print */
.email-caption {
  font-family: ${sansStack};
  font-size: 12px;
  line-height: 1.4;
  color: ${textMuted};
  margin: 0 0 8px 0;
}

/* ============================================================================
 * BUTTONS
 * ========================================================================== */

/* Primary CTA button */
.email-button-primary {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 16px;
  font-weight: 600;
  color: ${surface};
  background-color: ${primary};
  padding: 14px 28px;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  margin: 8px 0;
}

/* Secondary button (outline) */
.email-button-secondary {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 16px;
  font-weight: 600;
  color: ${primary};
  background-color: transparent;
  border: 2px solid ${primary};
  padding: 12px 26px;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  margin: 8px 0;
}

/* Success button */
.email-button-success {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 16px;
  font-weight: 600;
  color: ${surface};
  background-color: ${sustainability};
  padding: 14px 28px;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  margin: 8px 0;
}

/* Warning button */
.email-button-warning {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 16px;
  font-weight: 600;
  color: ${surface};
  background-color: ${amber};
  padding: 14px 28px;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  margin: 8px 0;
}

/* ============================================================================
 * LINKS
 * ========================================================================== */

.email-link {
  color: ${primary};
  text-decoration: underline;
  font-weight: 500;
}

/* ============================================================================
 * DIVIDERS & SPACING
 * ========================================================================== */

.email-divider {
  height: 1px;
  background-color: ${borderSubtle};
  border: none;
  margin: 24px 0;
}

.email-spacer-sm {
  height: 16px;
}

.email-spacer-md {
  height: 24px;
}

.email-spacer-lg {
  height: 40px;
}

/* ============================================================================
 * BADGES & ALERTS
 * ========================================================================== */

/* Success badge */
.email-badge-success {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 12px;
  font-weight: 600;
  color: ${sustainability};
  background-color: rgba(22, 163, 74, 0.1);
  padding: 4px 12px;
  border-radius: 12px;
}

/* Warning badge */
.email-badge-warning {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 12px;
  font-weight: 600;
  color: ${amber};
  background-color: rgba(249, 115, 22, 0.1);
  padding: 4px 12px;
  border-radius: 12px;
}

/* Critical badge */
.email-badge-critical {
  display: inline-block;
  font-family: ${sansStack};
  font-size: 12px;
  font-weight: 600;
  color: ${critical};
  background-color: rgba(220, 38, 38, 0.1);
  padding: 4px 12px;
  border-radius: 12px;
}

/* Alert box - Info */
.email-alert-info {
  background-color: rgba(14, 155, 167, 0.1);
  border-left: 4px solid ${primarySoft};
  padding: 16px;
  margin: 16px 0;
  border-radius: 4px;
}

/* Alert box - Success */
.email-alert-success {
  background-color: rgba(22, 163, 74, 0.1);
  border-left: 4px solid ${sustainability};
  padding: 16px;
  margin: 16px 0;
  border-radius: 4px;
}

/* Alert box - Warning */
.email-alert-warning {
  background-color: rgba(249, 115, 22, 0.1);
  border-left: 4px solid ${amber};
  padding: 16px;
  margin: 16px 0;
  border-radius: 4px;
}

/* Alert box - Critical */
.email-alert-critical {
  background-color: rgba(220, 38, 38, 0.1);
  border-left: 4px solid ${critical};
  padding: 16px;
  margin: 16px 0;
  border-radius: 4px;
}

/* ============================================================================
 * FOOTER
 * ========================================================================== */

.email-footer {
  font-family: ${sansStack};
  font-size: 12px;
  line-height: 1.5;
  color: ${textMuted};
  text-align: center;
  padding: 24px 16px;
  background-color: ${canvas};
}

.email-footer-link {
  color: ${textMuted};
  text-decoration: underline;
}

/* ============================================================================
 * INLINE STYLE REFERENCE
 * ========================================================================== */

/*
 * For maximum email client compatibility, use these inline styles directly:
 *
 * HEADINGS:
 * <h1 style="font-family: ${sansStack}; font-size: 32px; line-height: 1.2; letter-spacing: -0.02em; color: ${textMain}; margin: 0 0 16px 0; font-weight: 600;">
 *
 * BODY:
 * <p style="font-family: ${sansStack}; font-size: 16px; line-height: 1.6; color: ${textMain}; margin: 0 0 16px 0;">
 *
 * PRIMARY BUTTON:
 * <a href="#" style="display: inline-block; font-family: ${sansStack}; font-size: 16px; font-weight: 600; color: ${surface}; background-color: ${primary}; padding: 14px 28px; border-radius: 8px; text-decoration: none; text-align: center; margin: 8px 0;">
 *
 * LINK:
 * <a href="#" style="color: ${primary}; text-decoration: underline; font-weight: 500;">
 */
`;

  return cssContent;
}

/**
 * Main function to generate email CSS file
 */
function generateEmailCSSFile(): void {
  const cssContent = generateEmailCSS();

  // Ensure output directory exists
  const outputDir = path.resolve(__dirname, '../dist/tokens');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write CSS file
  const outputPath = path.join(outputDir, 'email-tokens.css');
  fs.writeFileSync(outputPath, cssContent, 'utf-8');

  const lineCount = cssContent.split('\n').length;
  console.log(`✅ Generated email CSS tokens: ${outputPath}`);
  console.log(`   ${lineCount} lines written`);
  console.log(`   Compatible with Gmail, Outlook, Apple Mail, Yahoo Mail`);
}

// Execute if run directly
if (require.main === module) {
  try {
    generateEmailCSSFile();
  } catch (error) {
    console.error('❌ Error generating email CSS:', error);
    process.exit(1);
  }
}

export { generateEmailCSSFile };
